/* =========================================================================
   Payroll & Purchase Requisitions — New-Staff Onboarding
   English ↔ Arabic translation dictionary (page content).
   Consumed by onboarding-i18n.js via window.AR_DICT. Hand-reviewed.
   ========================================================================= */
window.AR_DICT = {
    "AISA · New-Staff Onboarding": "AISA · تأهيل الموظفين الجدد",
    "Payroll & Purchase Requisitions": "الرواتب وطلبات الشراء",
    "How you get paid at AISA, and how to claim or request a purchase — straight from the Accounts Office.": "كيف تتقاضى راتبك في AISA، وكيف تطلب استرداداً أو تقدّم طلب شراء — مباشرةً من مكتب الحسابات.",
    "⏱ ~15 min": "⏱ ≈ 15 دقيقة",
    "📚 9 chapters": "📚 9 فصول",
    "✓ 2 knowledge checks": "✓ اختبارا فهم",
    "🎓 1 PD hour": "🎓 ساعة تطوير مهني واحدة",
    "🏛️ Accounts Office": "🏛️ مكتب الحسابات",
    "📎 View the original slide deck (PDF)": "📎 عرض العرض التقديمي الأصلي (PDF)",
    "Annex A/B/C forms & timing tables included": "نماذج الملحق A / الملحق B / الملحق C وجداول التوقيت مضمّنة",
    "Module Progress": "تقدّم الوحدة",
    "0% Done": "0% مكتمل",
    "Chapters": "الفصول",
    "Chapter 1": "الفصل 1",
    "What This Covers": "ما الذي تغطّيه هذه الوحدة",
    "Chapter 2": "الفصل 2",
    "Payroll Basics": "أساسيات الرواتب",
    "Chapter 3": "الفصل 3",
    "Submit Bank Details": "تقديم التفاصيل البنكية",
    "Chapter 4": "الفصل 4",
    "Knowledge Check 1": "اختبار الفهم 1",
    "Chapter 5": "الفصل 5",
    "Processing & Payment": "المعالجة والدفع",
    "Chapter 6": "الفصل 6",
    "Your Pay Slip": "قسيمة راتبك",
    "Chapter 7": "الفصل 7",
    "Purchase Requisitions": "طلبات الشراء",
    "Chapter 8": "الفصل 8",
    "Knowledge Check 2": "اختبار الفهم 2",
    "Chapter 9": "الفصل 9",
    "Quick Reference": "مرجع سريع",
    "Progress": "التقدّم",
    "Section 1": "القسم 1",
    "Two Things Every New Staff Member Needs to Know": "أمران يجب على كل موظف جديد معرفتهما",
    "Welcome to AISA. This short module covers the two Accounts Office processes that affect you from your very first month: how your": "مرحباً بك في AISA. تغطّي هذه الوحدة القصيرة عمليتي مكتب الحسابات اللتين تؤثّران عليك منذ شهرك الأول: كيف يعمل",
    "payroll": "نظام الرواتب",
    "works, and how to use a": "الخاص بك، وكيفية استخدام",
    "Purchase Requisition Form": "نموذج طلب الشراء",
    "when the school buys something for you or reimburses what you've paid.": "عندما تشتري المدرسة شيئاً لك أو تستردّ لك ما دفعته.",
    "Payroll Activities": "أنشطة الرواتب",
    "Submitting your bank account details": "تقديم تفاصيل حسابك البنكي",
    "How and when salaries are processed and paid": "كيف ومتى تتم معالجة الرواتب ودفعها",
    "Reading your monthly pay slip": "قراءة قسيمة راتبك الشهرية",
    "What a PRF is and who signs it": "ما هو نموذج طلب الشراء ومن يوقّعه",
    "What to attach for a direct supplier payment": "ما الذي يجب إرفاقه للدفع المباشر للمورّد",
    "What to attach to be reimbursed through payroll": "ما الذي يجب إرفاقه للاسترداد عبر الرواتب",
    "Where this comes from": "من أين يأتي هذا",
    "Both processes are run by the": "تُدار كلتا العمليتين من قِبل",
    "AISA Accounts Office": "مكتب الحسابات في AISA",
    ". Everything in this module reflects the orientation given to new staff — including the official forms (Annexes A, B and C) you'll see on the next screens.": ". كل ما في هذه الوحدة يعكس التوجيه المقدّم للموظفين الجدد — بما في ذلك النماذج الرسمية (الملاحق A وB وC) التي ستراها في الشاشات التالية.",
    "Section 2": "القسم 2",
    "Payroll Basics — Definition & the Three Activities": "أساسيات الرواتب — التعريف والأنشطة الثلاثة",
    "What \"payroll\" means": "ماذا تعني \"الرواتب\"",
    "Payroll is the": "الرواتب هي",
    "net amount of money paid on a monthly basis": "صافي المبلغ المالي المدفوع على أساس شهري",
    "to an employee for their earned salaries, allowances, stipends, reimbursements and deductions. As a function, it is the process by which employees receive their salary.": "للموظف مقابل رواتبه المكتسبة وبدلاته وعلاواته واستردادات ما دفعه وخصوماته. وكوظيفة، هي العملية التي يتقاضى الموظفون من خلالها رواتبهم.",
    "For you, payroll breaks down into": "بالنسبة لك، تنقسم الرواتب إلى",
    "three operating activities": "ثلاثة أنشطة تشغيلية",
    ":": ":",
    "One-time": "لمرة واحدة",
    "1. Submit bank account details": "1. تقديم تفاصيل الحساب البنكي",
    "Done once, as soon as possible after you join.": "يُنجز مرة واحدة، في أقرب وقت ممكن بعد انضمامك.",
    "Monthly": "شهرياً",
    "2. Processing & payment": "2. المعالجة والدفع",
    "Your salary is calculated and transferred each month.": "يُحتسب راتبك ويُحوّل كل شهر.",
    "3. Pay slip distribution": "3. توزيع قسيمة الراتب",
    "Your pay slip is emailed to you after each pay month.": "تُرسل قسيمة راتبك إليك عبر البريد الإلكتروني بعد كل شهر دفع.",
    "We'll walk through each of these in turn. The only one that needs action from you up front is the first.": "سنستعرض كل واحد منها تباعاً. الوحيد الذي يتطلّب إجراءً منك مسبقاً هو الأول.",
    "Section 3 · Your First Action": "القسم 3 · إجراؤك الأول",
    "Step 1: Submit Your Bank Account Details": "الخطوة 1: تقديم تفاصيل حسابك البنكي",
    "A one-time task — do this as soon as possible so your salary can be paid.": "مهمة لمرة واحدة — أنجزها في أقرب وقت ممكن حتى يتسنّى دفع راتبك.",
    "Who": "من",
    "Completed by": "يُكمله",
    "you": "أنت",
    ", the employee.": "، الموظف.",
    "When": "متى",
    "As soon as possible after joining.": "في أقرب وقت ممكن بعد الانضمام.",
    "Where": "أين",
    "To the": "إلى",
    "HR / Accounts Office": "مكتب الموارد البشرية / الحسابات",
    ", using the": "، باستخدام",
    "AISA Bank Account Form": "نموذج الحساب البنكي لـ AISA",
    "(Annex A).": "(الملحق A).",
    "How": "كيف",
    "Submit the completed Bank Account Form to the HR Office.": "قدّم نموذج الحساب البنكي المكتمل إلى مكتب الموارد البشرية.",
    "Why it's required": "لماذا هو مطلوب",
    "UAE law requires it. Under the Ministry of Human Resources & Emiratisation (MoHRE)": "يقتضيه القانون الإماراتي. بموجب وزارة الموارد البشرية والتوطين (MoHRE)",
    "Wages Protection System (WPS)": "نظام حماية الأجور (WPS)",
    "dirhams": "الدراهم",
    "and transferred to your": "وتُحوّل إلى",
    "UAE bank account": "حسابك البنكي الإماراتي",
    ". No valid local account on file means your salary can't be processed.": ". عدم وجود حساب محلي صالح مسجّل يعني تعذّر معالجة راتبك.",
    "What the bank needs to open your account": "ما يحتاجه البنك لفتح حسابك",
    "Bank form(s) for opening the account": "نموذج (نماذج) البنك لفتح الحساب",
    "Emirates ID": "الهوية الإماراتية",
    "Mobile phone number": "رقم الهاتف المحمول",
    "Annex A — Bank Account Form.": "الملحق A — نموذج الحساب البنكي.",
    "Fill in your account number, account name, bank name, IBAN, routing number and bank address, then sign and return it to HR.": "املأ رقم حسابك واسم الحساب واسم البنك والآيبان ورقم التوجيه وعنوان البنك، ثم وقّعه وأعِده إلى الموارد البشرية.",
    "Getting Paid": "تقاضي الراتب",
    "A new teacher hasn't submitted their AISA Bank Account Form yet but expects their first salary at the end of the month. What's the correct understanding?": "لم يقدّم معلّم جديد نموذج الحساب البنكي لـ AISA بعد، لكنه يتوقّع راتبه الأول في نهاية الشهر. ما الفهم الصحيح؟",
    "Salary can be paid in cash until the form is submitted.": "يمكن دفع الراتب نقداً حتى يتم تقديم النموذج.",
    "Salaries are paid through the WPS to a UAE bank account in dirhams, so the Bank Account Form must be submitted to HR as soon as possible.": "تُدفع الرواتب عبر نظام حماية الأجور (WPS) إلى حساب بنكي إماراتي بالدراهم، لذا يجب تقديم نموذج الحساب البنكي إلى الموارد البشرية في أقرب وقت ممكن.",
    "An overseas bank account is fine as long as it's in dirhams.": "لا بأس بحساب بنكي خارجي طالما أنه بالدراهم.",
    "The form only needs to be submitted at the end of the first year.": "لا يلزم تقديم النموذج إلا في نهاية السنة الأولى.",
    "Section 4": "القسم 4",
    "How & When Payroll Is Processed and Paid": "كيف ومتى تتم معالجة الرواتب ودفعها",
    "Payroll is managed by the": "تُدار الرواتب من قِبل",
    "Accounts Office": "مكتب الحسابات",
    ". The actual transfer of money to your bank account is made through the": ". يتم التحويل الفعلي للأموال إلى حسابك البنكي عبر",
    "WPS by the Central Bank": "نظام حماية الأجور (WPS) من قِبل المصرف المركزي",
    ", based on approved documents and in line with your contract and statutory requirements.": "، استناداً إلى المستندات المعتمدة وبما يتوافق مع عقدك والمتطلبات القانونية.",
    "Monthly payment timing": "توقيت الدفع الشهري",
    "1st year:": "السنة الأولى:",
    "August to May — paid at the end of each month.": "من أغسطس إلى مايو — يُدفع في نهاية كل شهر.",
    "2nd year onward:": "من السنة الثانية فصاعداً:",
    "August to July — paid at the end of each month.": "من أغسطس إلى يوليو — يُدفع في نهاية كل شهر.",
    "June:": "يونيو:",
    "50% paid; the rest of July's balance follows.": "يُدفع 50%؛ ويتبعه باقي رصيد يوليو.",
    "July:": "يوليو:",
    "paid on the last working day of the year; the July balance is settled by the end of August.": "يُدفع في آخر يوم عمل من السنة؛ ويُسوّى رصيد يوليو بنهاية أغسطس.",
    "Document processing windows": "نوافذ معالجة المستندات",
    "Aug–Nov:": "أغسطس–نوفمبر:",
    "15th to 22nd of the month.": "من 15 إلى 22 من الشهر.",
    "December:": "ديسمبر:",
    "5th to 7th of the month.": "من 5 إلى 7 من الشهر.",
    "Jan–May:": "يناير–مايو:",
    "10th to 12th of the month.": "من 10 إلى 12 من الشهر.",
    "Any change to your pay (stipend, leave, reimbursement) needs its document in": "أي تغيير على راتبك (بدل، إجازة، استرداد) يحتاج إلى تقديم مستنده",
    "before": "قبل",
    "that month's window to land in the same pay run.": "نافذة ذلك الشهر ليُدرج في دورة الدفع نفسها.",
    "What makes up your pay": "ممّ يتكوّن راتبك",
    "Each item is processed from an approved source document:": "تُعالج كل بنية من مستند مصدر معتمد:",
    "Normal pay (basic + allowances)": "الراتب العادي (الأساسي + البدلات)",
    "annual rate ÷ 12": "المعدّل السنوي ÷ 12",
    "+ Stipend": "+ بدل",
    "stipend document": "مستند البدل",
    "+ No-absence bonus": "+ مكافأة عدم الغياب",
    "HR report": "تقرير الموارد البشرية",
    "+ Summer ticket": "+ تذكرة الصيف",
    "cash-in-lieu offer": "عرض البدل النقدي",
    "+ Housing allowance": "+ بدل السكن",
    "housing form": "نموذج السكن",
    "+ Reimbursements": "+ الاستردادات",
    "purchase requisition form": "نموذج طلب الشراء",
    "− Unpaid leave": "− إجازة بدون أجر",
    "− Electricity & water": "− الكهرباء والماء",
    "ADDC bills": "فواتير ADDC",
    "Section 5": "القسم 5",
    "Your Monthly Pay Slip": "قسيمة راتبك الشهرية",
    "Handled by": "تتولّاها",
    "Accounts Office, through": "مكتب الحسابات، عبر",
    "Within": "خلال",
    "five days": "خمسة أيام",
    "after the pay month (latest).": "بعد شهر الدفع (كحدّ أقصى).",
    "Sent electronically from AISA Accounts to your": "تُرسل إلكترونياً من حسابات AISA إلى",
    "AISA email": "بريد AISA الإلكتروني الخاص بك",
    "Your pay slip reflects your net pay for the month — your normal (monthly) pay, monthly stipend, reimbursements and deductions. Check it each month against what you expect.": "تعكس قسيمة راتبك صافي راتبك للشهر — راتبك العادي (الشهري) والبدل الشهري والاستردادات والخصومات. راجِعها كل شهر مقابل ما تتوقّعه.",
    "Annex C — Sample pay slip.": "الملحق C — نموذج قسيمة راتب.",
    "A worked example: Basic + Allowances + Stipend totalling the Net Pay line (figures shown are illustrative only).": "مثال محلول: الأساسي + البدلات + البدل بمجموع يساوي بند صافي الراتب (الأرقام المعروضة توضيحية فقط).",
    "Section 6": "القسم 6",
    "The Purchase Requisition Form (PRF)": "نموذج طلب الشراء (PRF)",
    "is an internal control document showing that a particular purchase of goods and/or services is duly authorized. To be valid it must be signed by the": "هو مستند رقابة داخلية يبيّن أن شراءً معيّناً للسلع و/أو الخدمات مصرّح به حسب الأصول. ولكي يكون صالحاً يجب أن يوقّعه",
    "Principal": "المدير",
    ", the": "، و",
    "School Director": "مدير المدرسة",
    ", and the": "، و",
    "Business Manager": "مدير الأعمال",
    "(Annex B).": "(الملحق B).",
    "1. School pays the supplier directly": "1. المدرسة تدفع للمورّد مباشرةً",
    "Attach to the PRF:": "أرفِق بنموذج طلب الشراء:",
    "The invoice": "الفاتورة",
    "The supplier's bank account details": "تفاصيل الحساب البنكي للمورّد",
    "2. Reimbursement through your payroll": "2. الاسترداد عبر راتبك",
    "The invoice / proof of the charge": "الفاتورة / إثبات الرسم",
    "Proof of payment you made": "إثبات الدفع الذي قمت به",
    "The AISA PD application form, if using Professional Development money": "نموذج طلب التطوير المهني لـ AISA، إذا كنت تستخدم مخصّصات التطوير المهني",
    "Annex B — Purchase Requisition Form.": "الملحق B — نموذج طلب الشراء.",
    "Note the three approval signature blocks at the bottom: Principal, Director and Business Manager.": "لاحِظ خانات توقيع الاعتماد الثلاث في الأسفل: المدير ومدير المدرسة ومدير الأعمال.",
    "Tip": "نصيحة",
    "Reimbursements feed into payroll, so a PRF submitted after the month's document-processing window will be paid in the": "تُدرج الاستردادات في الرواتب، لذا فإن نموذج طلب الشراء المقدّم بعد نافذة معالجة مستندات الشهر سيُدفع في",
    "next": "التالية",
    "pay run. Submit early.": "دورة الدفع. قدّمه مبكراً.",
    "You paid out of pocket for an approved classroom resource and want to be reimbursed through your salary. Which is correct?": "دفعت من جيبك مقابل مورد صفّي معتمد وترغب في استرداده عبر راتبك. أيّها صحيح؟",
    "Email the Accounts Office the amount; no form or signatures are needed.": "أرسل المبلغ إلى مكتب الحسابات عبر البريد الإلكتروني؛ لا حاجة إلى نموذج أو توقيعات.",
    "Submit a PRF signed by the Principal, Director and Business Manager, attaching the invoice/proof of charge and proof of your payment.": "قدّم نموذج طلب شراء موقّعاً من المدير ومدير المدرسة ومدير الأعمال، مرفقاً به الفاتورة/إثبات الرسم وإثبات دفعك.",
    "A PRF is only for when the school pays a supplier directly, never for reimbursements.": "نموذج طلب الشراء مخصّص فقط عندما تدفع المدرسة لمورّد مباشرةً، وليس للاستردادات أبداً.",
    "Only the proof of payment is needed; the invoice can be skipped.": "إثبات الدفع وحده مطلوب؛ ويمكن تجاوز الفاتورة.",
    "Section 7": "القسم 7",
    "Quick Reference & Who to Contact": "مرجع سريع ومن تتواصل معه",
    "Do": "ما ينبغي فعله",
    "Submit your Bank Account Form (Annex A) to HR straight away.": "قدّم نموذج حسابك البنكي (الملحق A) إلى الموارد البشرية فوراً.",
    "Use a UAE dirham bank account for WPS.": "استخدم حساباً بنكياً إماراتياً بالدرهم لنظام حماية الأجور (WPS).",
    "Check your pay slip each month against what you expect.": "راجِع قسيمة راتبك كل شهر مقابل ما تتوقّعه.",
    "Get PRF signatures and attachments in before the monthly window.": "احصل على توقيعات ومرفقات نموذج طلب الشراء قبل النافذة الشهرية.",
    "Don't": "ما يجب تجنّبه",
    "Expect payment before your bank details are on file.": "توقّع الدفع قبل تسجيل تفاصيلك البنكية.",
    "Submit a PRF without all three approval signatures.": "تقديم نموذج طلب شراء دون توقيعات الاعتماد الثلاثة جميعها.",
    "Forget the invoice": "نسيان الفاتورة",
    "and": "و",
    "proof of payment on a reimbursement.": "إثبات الدفع في الاسترداد.",
    "Make verbal-only requests for anything that needs a paper trail.": "تقديم طلبات شفهية فقط لأي شيء يتطلّب أثراً ورقياً.",
    "Need help?": "بحاجة إلى مساعدة؟",
    "For any payroll or purchase-requisition question, contact": "لأي استفسار حول الرواتب أو طلبات الشراء، تواصل مع",
    "Sheila Gonzalez": "شيلا غونزاليس",
    "— at the": "— في",
    "Accounts Office, Ground Floor, Rotunda Area": "مكتب الحسابات، الطابق الأرضي، منطقة الروتوندا",
    "Keep for reference": "احتفِظ به للرجوع إليه",
    "Open the original Accounts Office orientation deck (PDF)": "افتح العرض التوجيهي الأصلي لمكتب الحسابات (PDF)",
    "for the full Annex A, B and C forms you can print and fill in.": "للحصول على نماذج الملحق A وB وC الكاملة التي يمكنك طباعتها وملؤها.",
    "Previous": "السابق",
    "Chapter 1 of 9": "الفصل 1 من 9",
    "Next chapter": "الفصل التالي",
    "Module Complete!": "اكتملت الوحدة!",
    "You now know how AISA payroll works and how to use a Purchase Requisition Form. Get your Bank Account Form to HR if you haven't already — that's the one thing to do today.": "أنت الآن تعرف كيف يعمل نظام الرواتب في AISA وكيفية استخدام نموذج طلب الشراء. أوصِل نموذج حسابك البنكي إلى الموارد البشرية إن لم تكن قد فعلت — فهذا هو الشيء الوحيد الذي ينبغي فعله اليوم.",
    "Return to Modules": "العودة إلى الوحدات",
    "AISA — American International School in Abu Dhabi": "AISA — المدرسة الأمريكية الدولية في أبوظبي",
    "New-Staff Onboarding | Payroll & Purchase Requisitions · Accounts Office": "تأهيل الموظفين الجدد | الرواتب وطلبات الشراء · مكتب الحسابات",
    "This module summarises Accounts Office orientation. For your specific situation, always confirm with the Accounts Office.": "تلخّص هذه الوحدة توجيه مكتب الحسابات. وبالنسبة لحالتك الخاصة، تأكّد دائماً من مكتب الحسابات.",
    "The Learning Hub": "مركز التعلّم",
    "Sign in with your": "سجّل الدخول باستخدام",
    "Google account to continue.": "حساب Google للمتابعة.",
    "Could not reach Google sign-in. Are you offline?": "تعذّر الوصول إلى تسجيل الدخول عبر Google. هل أنت غير متّصل بالإنترنت؟",
    "AISA staff & faculty access only.": "الوصول مقتصر على موظفي وأعضاء هيئة التدريس في AISA فقط.",
    "Annex A — AISA Bank Account Form, addressed to the School Director, with fields for account number, account name, bank name, IBAN, routing number and bank address.": "الملحق A — نموذج الحساب البنكي لـ AISA، موجّه إلى مدير المدرسة، مع حقول لرقم الحساب واسم الحساب واسم البنك والآيبان ورقم التوجيه وعنوان البنك.",
    "Annex C — Sample AISA pay slip showing Payslip month, Employee ID and name, then Basic, Allowances and Stipend lines adding up to Net Pay in AED.": "الملحق C — نموذج قسيمة راتب لـ AISA يعرض شهر القسيمة ومعرّف الموظف واسمه، ثم بنود الأساسي والبدلات والبدل بمجموع يساوي صافي الراتب بالدرهم.",
    "Annex B — AISA Purchase Requisition Form with date, requisitioner, department, an itemised table of description, quantity, unit price and amount, plus signature blocks for Principal, Director and Business Manager approval.": "الملحق B — نموذج طلب الشراء لـ AISA مع التاريخ ومقدّم الطلب والقسم، وجدول مفصّل بالوصف والكمية وسعر الوحدة والمبلغ، إضافةً إلى خانات توقيع لاعتماد المدير ومدير المدرسة ومدير الأعمال.",
    "Sign in required": "تسجيل الدخول مطلوب",
    "Loading sign-in": "جارٍ تحميل تسجيل الدخول",
    ", salaries must be paid in": "، يجب أن تُدفع الرواتب إلى"
};
