/* =========================================================================
   Child Safeguarding & Protection — Annual Staff Training
   English ↔ Arabic translation dictionary (page content).
   Consumed by onboarding-i18n.js via window.AR_DICT. Hand-reviewed.
   ========================================================================= */
window.AR_DICT = {
    "AISA · Required Safeguarding Training": "AISA · تدريب حماية الطفل الإلزامي",
    "Child Safeguarding & Protection": "حماية الطفل ورعايته",
    "Safeguarding is everyone's responsibility. Learn to recognise concerns, respond well, and report them — the welfare of the child is always paramount.": "حماية الطفل مسؤولية الجميع. تعلّم كيف تتعرّف على المخاوف، وتتجاوب معها بشكل سليم، وتبلّغ عنها — فمصلحة الطفل هي الأولوية القصوى دائمًا.",
    "⏱ ~30 min": "⏱ ≈ 30 دقيقة",
    "📚 12 chapters": "📚 12 فصلًا",
    "✓ 3 knowledge checks": "✓ 3 اختبارات فهم",
    "🎓 2 PD hours": "🎓 ساعتا تطوير مهني",
    "🔴 Required annually": "🔴 إلزامي سنويًا",
    "📝 Complete the mandatory acknowledgment form": "📝 أكمل نموذج الإقرار الإلزامي",
    "Safeguarding Committee · reviewed annually": "لجنة حماية الطفل · تُراجَع سنويًا",
    "Module Progress": "تقدّم الوحدة",
    "0% Done": "0% مكتمل",
    "Section 1": "القسم 1",
    "Why Safeguarding Matters": "لماذا تهمّ الحماية الوقائية للطفل",
    "AISA is committed to a": "تلتزم AISA بتوفير",
    "safe, inclusive and respectful": "بيئة آمنة وشاملة ومحترمة",
    "environment for every student. Safeguarding is not a single role — it is a shared responsibility held by every member of staff.": "لكل طالب. والحماية الوقائية للطفل ليست دورًا منفردًا — بل هي مسؤولية مشتركة يحملها كل فرد من أفراد طاقم العمل.",
    "⚖️": "⚖️",
    "The guiding principle": "المبدأ التوجيهي",
    "The": "إنّ",
    "welfare of the child is paramount": "مصلحة الطفل هي الأولوية القصوى",
    ". It is a principle of UAE law and child-protection procedure that the protection and welfare of students must always come first.": ". فمن مبادئ قانون دولة الإمارات وإجراءات حماية الطفل أن تكون حماية الطلاب ورعايتهم في المقام الأول دائمًا.",
    "📜": "📜",
    "The frameworks we follow": "الأطر التي نتّبعها",
    "Wadeema's Law": "قانون وديمة",
    "— UAE Federal Law No. 3 of 2016 (Child Rights)": "— القانون الاتحادي رقم 3 لسنة 2016 (حقوق الطفل)",
    "ADEK": "ADEK",
    "safeguarding regulations": "لوائح حماية الطفل",
    "ITFCP": "ITFCP",
    "— Inter-agency framework for child protection": "— الإطار المشترك بين الجهات لحماية الطفل",
    "UK": "المملكة المتحدة",
    "“Keeping Children Safe in Education”": "«الحفاظ على سلامة الأطفال في التعليم»",
    "(KCSIE)": "(KCSIE)",
    "🧭": "🧭",
    "Our guiding principles": "مبادئنا التوجيهية",
    "Equal protection for": "حماية متساوية لـ",
    "all": "جميع",
    "students.": "الطلاب.",
    "Students should feel safe": "ينبغي أن يشعر الطلاب بالأمان",
    "physically, emotionally and digitally": "جسديًا وعاطفيًا ورقميًا",
    ".": ".",
    "All concerns are taken seriously, acted on promptly, and kept confidential.": "تؤخذ جميع المخاوف على محمل الجدّ، ويُتعامل معها بسرعة، وتبقى سرّية.",
    "We work in partnership with families, authorities and agencies.": "نعمل بالشراكة مع الأسر والسلطات والجهات المختصة.",
    "Safeguarding at AISA is reviewed annually by the Governing Board and the Safeguarding Committee.": "تُراجَع الحماية الوقائية للطفل في AISA سنويًا من قبل مجلس الإدارة ولجنة حماية الطفل.",
    "Section 2": "القسم 2",
    "Watch: The Safeguarding Briefing": "شاهد: الإحاطة التعريفية بحماية الطفل",
    "🎬": "🎬",
    "Safeguarding briefing video": "فيديو الإحاطة التعريفية بحماية الطفل",
    "The video accompanies this training. Once it's uploaded it will play right here — your DSL will let you know when it's ready.": "يرافق هذا الفيديو هذا التدريب. وبمجرد رفعه سيُعرض هنا مباشرة — وسيُعلِمك مسؤول حماية الطفل المعتمد (DSL) عندما يكون جاهزًا.",
    "While you watch (or read on if the video isn't up yet):": "أثناء المشاهدة (أو تابع القراءة إن لم يُرفع الفيديو بعد):",
    "notice": "لاحظ",
    "how": "كيف",
    "staff are expected to respond to a concern — calmly, without judgement, and by reporting to the DSL. The chapters that follow give you the exact steps.": "يُتوقّع من طاقم العمل التجاوب مع أي مصدر قلق — بهدوء، ودون إصدار أحكام، ومن خلال الإبلاغ لمسؤول حماية الطفل المعتمد (DSL). وتقدّم لك الفصول التالية الخطوات الدقيقة.",
    "Section 3": "القسم 3",
    "Key Definitions": "التعريفات الأساسية",
    "Safeguarding": "الحماية الوقائية للطفل",
    "proactive": "الاستباقية",
    "steps we take to prevent harm before it happens.": "الخطوات التي نتّخذها لمنع وقوع الأذى قبل حدوثه.",
    "🚨": "🚨",
    "Child Protection": "حماية الطفل",
    "specific actions": "الإجراءات المحدّدة",
    "we take when harm is suspected or confirmed.": "التي نتّخذها عند الاشتباه في وقوع أذى أو التأكّد منه.",
    "⚠️": "⚠️",
    "The four types of abuse": "أنواع الإساءة الأربعة",
    "Physical": "الجسدية",
    "Emotional": "العاطفية",
    "Sexual / Exploitation": "الجنسية أو الاستغلال",
    "Neglect": "الإهمال",
    "🧩": "🧩",
    "ALN — Additional Learning Needs": "ALN — احتياجات التعلّم الإضافية",
    "Support a student may need": "الدعم الذي قد يحتاجه الطالب",
    "beyond typical classroom instruction": "بما يتجاوز التعليم الصفّي المعتاد",
    ". Safeguarding and inclusion work hand in hand.": ". وتعمل الحماية الوقائية للطفل والدمج جنبًا إلى جنب.",
    "Section 4": "القسم 4",
    "Roles & Responsibilities": "الأدوار والمسؤوليات",
    "Designated Safeguarding Lead (DSL)": "مسؤول حماية الطفل المعتمد (DSL)",
    "Oversees safeguarding, trains staff, and maintains records.": "يشرف على الحماية الوقائية للطفل، ويدرّب طاقم العمل، ويحتفظ بالسجلات.",
    "Every concern is reported to the DSL.": "يُبلَّغ عن كل مصدر قلق لمسؤول حماية الطفل المعتمد (DSL).",
    "Safeguarding Committee": "لجنة حماية الطفل",
    "Counsellor, Nurse, Head of Inclusion, Health & Safety Officer, and Divisional Leaders.": "المرشد الطلابي، والممرضة، ورئيس قسم الدمج، ومسؤول الصحة والسلامة، وقادة الأقسام.",
    "👥": "👥",
    "All staff & volunteers — that means you": "جميع أفراد طاقم العمل والمتطوعين — أي أنت",
    "Complete annual safeguarding training.": "أكمل تدريب حماية الطفل السنوي.",
    "Report concerns": "أبلِغ عن المخاوف",
    "immediately": "فورًا",
    "to the DSL.": "لمسؤول حماية الطفل المعتمد (DSL).",
    "Follow the Code of Conduct and confidentiality at all times.": "التزم بميثاق السلوك والسرية في جميع الأوقات.",
    "Avoid private one-to-one interactions with students behind closed doors.": "تجنّب التفاعلات الفردية الخاصة مع الطلاب خلف أبواب مغلقة.",
    "Knowledge Check 1": "اختبار الفهم 1",
    "Your Responsibility": "مسؤوليتك",
    "A student tells you something during a lesson that makes you worried about their safety at home. What is your responsibility?": "يخبرك طالب بشيء أثناء الحصة يجعلك قلقًا على سلامته في المنزل. ما هي مسؤوليتك؟",
    "Investigate it yourself first, and only involve others if you find evidence.": "أن تحقّق في الأمر بنفسك أولًا، ولا تُشرِك الآخرين إلا إذا وجدت دليلًا.",
    "Report the concern to the DSL immediately — safeguarding is everyone's responsibility, and the DSL decides what happens next.": "أن تبلّغ عن المخاوف لمسؤول حماية الطفل المعتمد (DSL) فورًا — فحماية الطفل مسؤولية الجميع، وهو من يقرّر ما يحدث بعد ذلك.",
    "Wait to see if the student mentions it again before doing anything.": "أن تنتظر لترى إن كان الطالب سيذكر الأمر مرة أخرى قبل أن تفعل أي شيء.",
    "Promise the student you'll keep it completely secret.": "أن تَعِد الطالب بأنك ستبقي الأمر سرًّا تامًّا.",
    "Section 5 · Critical": "القسم 5 · بالغ الأهمية",
    "Reporting & Whistleblowing": "الإبلاغ والإبلاغ عن المخالفات",
    "⏱️": "⏱️",
    "The 24-hour rule": "قاعدة الـ 24 ساعة",
    "Report suspected abuse": "أبلِغ عن الإساءة المشتبه بها",
    "within 24 hours": "خلال 24 ساعة",
    ". All reporting goes to the": ". ويُوجَّه كل إبلاغ إلى",
    "DSL / Principal": "مسؤول حماية الطفل المعتمد (DSL) / مدير المدرسة",
    "for your division.": "في قسمك.",
    "You are protected": "أنت محميّ",
    "Whistleblowers are": "إنّ المُبلِّغين عن المخالفات",
    "legally protected": "محميّون قانونًا",
    "in the UAE.": "في دولة الإمارات.",
    "To stay anonymous, a reporter must": "وللبقاء مجهول الهوية، يجب على المُبلِّغ أن",
    "explicitly request": "يطلب ذلك صراحةً",
    "it.": "ذلك.",
    "It is a legal duty": "إنه واجب قانوني",
    "Under UAE law, a": "بموجب قانون دولة الإمارات، فإنّ",
    "mandated reporter who fails to report": "المُبلِّغ المُلزَم قانونًا الذي يتخلّف عن الإبلاغ",
    "is subject to fines and possible legal action. When in doubt, report.": "يكون عرضة للغرامات واحتمال اتخاذ إجراءات قانونية. وعند الشكّ، أبلِغ.",
    "📞": "📞",
    "External child-protection contacts": "جهات الاتصال الخارجية لحماية الطفل",
    "Emergency": "الطوارئ",
    "MOI Child Protection Hotline": "الخط الساخن لحماية الطفل بوزارة الداخلية",
    "Online": "الموقع الإلكتروني",
    "Email": "البريد الإلكتروني",
    "🔒": "🔒",
    "Strict confidentiality": "السرية التامة",
    "AISA employees are": "إنّ موظفي AISA",
    "strictly prohibited": "ممنوعون منعًا باتًّا",
    "from discussing active or closed cases with any third party — including other employees and the media.": "من مناقشة الحالات النشطة أو المغلقة مع أي طرف ثالث — بما في ذلك الموظفون الآخرون ووسائل الإعلام.",
    "Section 6": "القسم 6",
    "Responding to a Disclosure — the 5 R's": "التجاوب مع الإفصاح — خطوات الاستجابة الخمس",
    "If a student discloses something to you, follow these five steps.": "إذا أفصح لك طالب عن شيء، فاتّبع هذه الخطوات الخمس.",
    "Receive": "الإصغاء",
    "Listen carefully,": "أصغِ بعناية،",
    "without judgment": "دون إصدار أحكام",
    "Reassure": "الطمأنة",
    "Affirm that speaking up was right.": "أكّد أن البوح بالأمر كان تصرّفًا صائبًا.",
    "Don't make promises": "لا تقطع وعودًا",
    "you can't keep.": "لا يمكنك الوفاء بها.",
    "React": "التجاوب",
    "Don't investigate. Ask only": "لا تحقّق. واطرح فقط",
    "open-ended": "أسئلة مفتوحة",
    "questions if you need to.": "إذا احتجت إلى ذلك.",
    "Record": "التوثيق",
    "Write the child's": "دوِّن",
    "exact words": "الكلمات الدقيقة للطفل",
    ", date, time and location — right after, not in front of the child.": "، والتاريخ والوقت والمكان — فور انتهاء الحديث، وليس أمام الطفل.",
    "Report": "الإبلاغ",
    "Notify the": "أبلِغ",
    "DSL": "مسؤول حماية الطفل المعتمد (DSL)",
    "and file the report internally with them.": "وقدّم التقرير داخليًا معه.",
    "✅": "✅",
    "Do": "افعل",
    "Listen empathetically and non-judgmentally.": "أصغِ بتعاطف ودون إصدار أحكام.",
    "Observe the student; let them know they are believed.": "راقِب الطالب؛ وأشعِره بأنه مُصدَّق.",
    "Let them know who they can trust.": "أعلِمه بمن يمكنه الوثوق به.",
    "Work closely with the counsellor / admin.": "اعمل عن كثب مع المرشد الطلابي / الإدارة.",
    "🚫": "🚫",
    "Don't": "لا تفعل",
    "Ask probing or leading questions.": "أن تطرح أسئلة استقصائية أو موجِّهة.",
    "Try to counsel the student yourself.": "أن تحاول إرشاد الطالب بنفسك.",
    "Tell people who don't need to know.": "أن تُخبر أشخاصًا ليسوا بحاجة إلى المعرفة.",
    "Assume it isn't true and fail to report.": "أن تفترض أن الأمر غير صحيح وتتخلّف عن الإبلاغ.",
    "🤐": "🤐",
    "On confidentiality with students": "بشأن السرية مع الطلاب",
    "Never guarantee absolute confidentiality. It's better to say you": "لا تضمن أبدًا سرية مطلقة. فمن الأفضل أن تقول إنك",
    "might have to tell someone whose job is to keep them safe": "قد تضطر إلى إخبار شخص مهمته الحفاظ على سلامته",
    ". Don't keep anything illegal, damaging or threatening covered up — and don't engage students who come to complain about other staff; pass it to the DSL.": ". ولا تتستّر على أي أمر غير قانوني أو ضارّ أو يشكّل تهديدًا — ولا تتعامل مع الطلاب الذين يأتون للشكوى من أفراد آخرين في طاقم العمل؛ بل أحِل الأمر إلى مسؤول حماية الطفل المعتمد (DSL).",
    "Knowledge Check 2": "اختبار الفهم 2",
    "Receiving a Disclosure": "تلقّي الإفصاح",
    "A student starts to disclose something serious and asks, \"Promise you won't tell anyone?\" Which response best follows the 5 R's?": "يبدأ طالب في الإفصاح عن أمر خطير ويسأل: «أتعدني بألا تخبر أحدًا؟» أيّ ردّ يتوافق على أفضل وجه مع خطوات الاستجابة الخمس؟",
    "\"I'm really glad you told me. I can't promise to keep it secret because I might need to tell someone whose job is to keep you safe — but I'll help you.\"": "«أنا سعيد حقًا لأنك أخبرتني. لا يمكنني أن أَعِد بإبقاء الأمر سرًّا لأنني قد أحتاج إلى إخبار شخص مهمته الحفاظ على سلامتك — لكنني سأساعدك.»",
    "\"Yes, I promise this stays just between us.\"": "«نعم، أعِدك بأن يبقى هذا بيننا فقط.»",
    "Ask lots of detailed questions to find out exactly what happened before deciding whether it's worth reporting.": "اطرح الكثير من الأسئلة التفصيلية لمعرفة ما حدث بالضبط قبل أن تقرّر ما إذا كان الأمر يستحق الإبلاغ.",
    "Tell them you're not the right person and they should speak to a friend instead.": "أخبره بأنك لست الشخص المناسب وأن عليه التحدّث إلى صديق بدلًا من ذلك.",
    "Section 7": "القسم 7",
    "Types of Abuse & Risk Factors": "أنواع الإساءة وعوامل الخطر",
    "It is everyone's responsibility to protect students' wellbeing — and at times,": "إنّ حماية رفاه الطلاب مسؤولية الجميع — وفي بعض الأحيان،",
    "you are the first responder": "تكون أنت أول مُستجيب",
    ". Harm can include threats from those responsible for a child's care:": ". وقد يشمل الأذى تهديدات من المسؤولين عن رعاية الطفل:",
    "family members, guardians, or other adults": "أفراد الأسرة أو الأوصياء أو غيرهم من البالغين",
    "in the student's life.": "في حياة الطالب.",
    "✋": "✋",
    "💔": "💔",
    "🥪": "🥪",
    "📈": "📈",
    "Risk factors to be alert to": "عوامل الخطر التي ينبغي الانتباه لها",
    "Social isolation": "العزلة الاجتماعية",
    "Trauma — death/illness, divorce or forced separation, witnessing violence": "الصدمات — الوفاة/المرض، أو الطلاق أو الفصل القسري، أو مشاهدة العنف",
    "Loss of protective community mechanisms": "فقدان آليات الحماية المجتمعية",
    "🔎": "🔎",
    "Harm isn't always visible": "الأذى ليس مرئيًا دائمًا",
    "Adverse Childhood Experiences (ACE) research shows that children from": "تُظهر أبحاث تجارب الطفولة السلبية (ACE) أن الأطفال من",
    "affluent families": "الأسر الميسورة",
    "can suffer hidden harm in less visible ways (Felitti et al., 1998). Stay alert across every community, and consider each situation through a thoughtful": "قد يعانون من أذى خفيّ بطرق أقل وضوحًا (Felitti et al., 1998). فابقَ يقظًا في كل مجتمع، وانظر إلى كل موقف من خلال",
    "cultural lens": "منظور ثقافي متأنٍّ",
    "Section 8 · Handle with care": "القسم 8 · يُتعامل معه بعناية",
    "Self-Harm & Suicide": "إيذاء النفس والانتحار",
    "It's okay to not be okay. Your calm, prompt response can save a life.": "لا بأس بأن تكون غير بخير. فتجاوبك الهادئ والسريع قد ينقذ حياة.",
    "Self-harm is when someone hurts themselves to cope with very difficult feelings, painful memories or overwhelming situations. It can be a way to make invisible pain visible, to feel in control, or to express suicidal feelings": "إيذاء النفس هو أن يؤذي الشخص نفسه للتعامل مع مشاعر بالغة الصعوبة، أو ذكريات مؤلمة، أو مواقف لا تُحتمل. وقد يكون وسيلة لجعل الألم غير المرئي مرئيًا، أو للشعور بالسيطرة، أو للتعبير عن مشاعر انتحارية",
    "without": "دون",
    "acting on them. Approach it without judgement.": "أن يقدم عليها. وتعامل مع الأمر دون إصدار أحكام.",
    "👀": "👀",
    "Possible signs of self-harm": "علامات محتملة لإيذاء النفس",
    "Heavy scratching in one area; unexplained cuts or bruising": "خدوش كثيفة في منطقة واحدة؛ أو جروح أو كدمات غير مبرّرة",
    "Cuts/scratches to arms, thighs or torso (easily hidden)": "جروح/خدوش في الذراعين أو الفخذين أو الجذع (يسهل إخفاؤها)",
    "Bruising to knuckles or forehead": "كدمات في مفاصل الأصابع أو الجبين",
    "Oddly placed or repeated burn marks": "آثار حروق في أماكن غريبة أو متكررة",
    "Multiple plasters/coverings over one area": "لصقات/أغطية متعددة فوق منطقة واحدة",
    "Suicide warning signs": "العلامات التحذيرية للانتحار",
    "Talking, writing, texting or drawing about wanting to die": "الحديث أو الكتابة أو المراسلة أو الرسم عن الرغبة في الموت",
    "Planning (notes, researching methods)": "التخطيط (كتابة ملاحظات، البحث عن وسائل)",
    "Harming self; expressing hopelessness": "إيذاء النفس؛ التعبير عن فقدان الأمل",
    "Severe emotional pain or distress": "ألم عاطفي شديد أو ضائقة شديدة",
    "Marked behaviour changes — withdrawal, sleep changes, anger, agitation": "تغيّرات سلوكية ملحوظة — الانعزال، تغيّرات النوم، الغضب، الهياج",
    "Responding to self-harm": "التجاوب مع إيذاء النفس",
    "Remain calm.": "حافظ على هدوئك.",
    "Listen with empathy — no judgement, don't question their reasons.": "أصغِ بتعاطف — دون إصدار أحكام، ولا تشكّك في أسبابه.",
    "Inform the assigned counsellor.": "أبلِغ المرشد الطلابي المعنيّ.",
    "🆘": "🆘",
    "If you believe a student may be suicidal": "إذا اعتقدت أن طالبًا قد يكون لديه ميول انتحارية",
    "Maintain": "حافظ على",
    "direct physical supervision": "إشراف جسدي مباشر",
    "of the student.": "على الطالب.",
    "Immediately contact the Safeguarding Lead.": "اتصل فورًا بمسؤول حماية الطفل.",
    "Do NOT wait until class is over or the end of the day.": "لا تنتظر حتى انتهاء الحصة أو نهاية اليوم.",
    "Section 9": "القسم 9",
    "Digital Safety, Records & AI": "السلامة الرقمية والسجلات والذكاء الاصطناعي",
    "📹": "📹",
    "Security & digital safety": "الأمن والسلامة الرقمية",
    "CCTV in all classrooms and main campus areas.": "كاميرات مراقبة (CCTV) في جميع الفصول الدراسية ومناطق الحرم الرئيسية.",
    "Visitor ID, sign-in and badge requirements.": "متطلبات تحديد هوية الزائر، والتسجيل، وحمل البطاقة التعريفية.",
    "No sharing of student data on personal devices or unapproved platforms.": "عدم مشاركة بيانات الطلاب على الأجهزة الشخصية أو المنصات غير المعتمدة.",
    "🗄️": "🗄️",
    "Confidentiality & record keeping": "السرية وحفظ السجلات",
    "Secure digital storage, separate from academic files.": "تخزين رقمي آمن، منفصل عن الملفات الأكاديمية.",
    "Access only by the DSL and one identified additional safeguarding member.": "الوصول مقتصر على مسؤول حماية الطفل المعتمد (DSL) وعضو إضافي محدّد واحد من فريق حماية الطفل.",
    "Staff must": "يجب على طاقم العمل",
    "not": "ألا",
    "keep personal copies of reports.": "يحتفظوا بنسخ شخصية من التقارير.",
    "🤖": "🤖",
    "Essential guidelines for AI usage": "إرشادات أساسية لاستخدام الذكاء الاصطناعي",
    "Never input student names, contact details or unique identifiers.": "لا تُدخِل أبدًا أسماء الطلاب أو بيانات التواصل أو المعرّفات الفريدة.",
    "Use only school-approved, privacy-verified AI platforms.": "استخدم فقط منصات الذكاء الاصطناعي المعتمدة من المدرسة والمتحقّق من خصوصيتها.",
    "Follow data-minimisation principles.": "اتّبع مبادئ تقليل البيانات إلى الحدّ الأدنى.",
    "Use pseudonyms (e.g. \"Student A\") instead of real names.": "استخدم أسماء مستعارة (مثل «الطالب أ») بدلًا من الأسماء الحقيقية.",
    "Remove identifying details before inputting student work.": "أزِل التفاصيل التي تحدّد الهوية قبل إدخال عمل الطالب.",
    "Never share grades, health data or behavioural information.": "لا تشارك أبدًا الدرجات أو البيانات الصحية أو المعلومات السلوكية.",
    "Section 10": "القسم 10",
    "Your Safeguarding Team & Counsellors": "فريق حماية الطفل والمرشدون الطلابيون لديك",
    "Elementary Safeguarding Team": "فريق حماية الطفل للمرحلة الابتدائية",
    "— Assistant Principal,": "— مساعد مدير المدرسة،",
    "Safeguarding Lead (DSL)": "مسؤول حماية الطفل (DSL)",
    "Counsellors: Dr. Mildred Stevenson · Sara AlBeainy": "المرشدون الطلابيون: Dr. Mildred Stevenson · Sara AlBeainy",
    "Nurses: Jothi Vinod · Kaviya Sasikumar": "الممرضات: Jothi Vinod · Kaviya Sasikumar",
    "Secondary Safeguarding Team": "فريق حماية الطفل للمرحلة الثانوية",
    "— MS Assistant Principal,": "— مساعد مدير المرحلة المتوسطة،",
    "Counsellors: Taj Coleman (HS) · Jenn Guss (HS) · Joel Hunter (MS)": "المرشدون الطلابيون: Taj Coleman (HS) · Jenn Guss (HS) · Joel Hunter (MS)",
    "🧑‍🏫": "🧑‍🏫",
    "When to refer a student to a counsellor": "متى تُحيل طالبًا إلى المرشد الطلابي",
    "You're concerned about a student's mood, behaviour or emotional needs.": "عندما تكون قلقًا بشأن مزاج الطالب أو سلوكه أو احتياجاته العاطفية.",
    "A student shares — or you suspect — thoughts of self-harm.": "عندما يبوح الطالب — أو تشتبه أنت — بأفكار حول إيذاء النفس.",
    "A parent shares a challenging home/family circumstance.": "عندما يطلعك أحد أولياء الأمور على ظرف منزلي/أسري صعب.",
    "A student lacks friendships or has poor social skills.": "عندما يفتقر الطالب إلى الصداقات أو تكون مهاراته الاجتماعية ضعيفة.",
    "Known or suspected medical / mental-health needs.": "عند وجود احتياجات طبية / متعلقة بالصحة النفسية معروفة أو مشتبه بها.",
    "You'd like support addressing a topic with your class.": "عندما ترغب في الحصول على دعم لتناول موضوع ما مع صفّك.",
    "Email the counsellor with your referral. Counsellors provide short-term support, crisis response and risk assessments — they do not counsel staff or issue consequences for students. Anything safeguarding-related still goes to the DSL.": "راسِل المرشد الطلابي بالبريد الإلكتروني بإحالتك. يقدّم المرشدون الطلابيون الدعم قصير المدى، والتجاوب مع الأزمات، وتقييمات المخاطر — وهم لا يقدّمون الإرشاد لطاقم العمل ولا يفرضون عقوبات على الطلاب. وأي أمر يتعلق بحماية الطفل يُوجَّه دائمًا إلى مسؤول حماية الطفل المعتمد (DSL).",
    "Knowledge Check 3": "اختبار الفهم 3",
    "A Student in Crisis": "طالب في أزمة",
    "Mid-lesson, a student hands you a note suggesting they are thinking about ending their life. What do you do?": "في منتصف الحصة، يناولك طالب ورقة توحي بأنه يفكّر في إنهاء حياته. ماذا تفعل؟",
    "Finish the lesson, then email the counsellor at the end of the day.": "أن تُنهي الحصة، ثم تراسل المرشد الطلابي بالبريد الإلكتروني في نهاية اليوم.",
    "Send the student to the counsellor's office on their own.": "أن ترسل الطالب بمفرده إلى مكتب المرشد الطلابي.",
    "Keep the student under direct physical supervision and immediately contact the Safeguarding Lead — do not wait.": "أن تُبقي الطالب تحت إشراف جسدي مباشر وتتصل فورًا بمسؤول حماية الطفل — دون انتظار.",
    "Ask the student in front of the class whether they really mean it.": "أن تسأل الطالب أمام الصف عمّا إذا كان يعني ذلك حقًّا.",
    "Section 11 · Mandatory": "القسم 11 · إلزامي",
    "Complete Your Mandatory Acknowledgment": "أكمل إقرارك الإلزامي",
    "As a": "بوصفه",
    "mandatory requirement": "متطلبًا إلزاميًا",
    ", complete the safeguarding acknowledgment form to confirm you've finished this training. Scan the QR code or use the button below.": "، أكمل نموذج إقرار حماية الطفل لتأكيد إنهائك هذا التدريب. امسح رمز الاستجابة السريعة أو استخدم الزرّ أدناه.",
    "📝 Open the acknowledgment form": "📝 افتح نموذج الإقرار",
    "Remember the essentials: safeguarding is everyone's responsibility · report to the DSL within 24 hours · never promise secrecy · the welfare of the child is paramount.": "تذكّر الأساسيات: حماية الطفل مسؤولية الجميع · أبلِغ مسؤول حماية الطفل المعتمد (DSL) خلال 24 ساعة · لا تَعِد أبدًا بالسرية · مصلحة الطفل هي الأولوية القصوى.",
    "Scan to open the acknowledgment form": "امسح الرمز لفتح نموذج الإقرار",
    "Training Complete!": "اكتمل التدريب!",
    "Thank you for protecting our students. If you haven't yet, complete the mandatory acknowledgment form — and remember: when in doubt, report to your DSL. Safeguarding is everyone's responsibility.": "شكرًا لك على حماية طلابنا. إن لم تكن قد فعلت بعد، فأكمل نموذج الإقرار الإلزامي — وتذكّر: عند الشكّ، أبلِغ مسؤول حماية الطفل المعتمد (DSL) لديك. فحماية الطفل مسؤولية الجميع.",
    "Return to Modules": "العودة إلى الوحدات",
    "AISA — American International School in Abu Dhabi": "AISA — المدرسة الأمريكية الدولية في أبوظبي",
    "Required Training | Child Safeguarding & Protection · Safeguarding Committee": "تدريب إلزامي | حماية الطفل ورعايته · لجنة حماية الطفل",
    "If a child is in immediate danger, call 999. Report all safeguarding concerns to your DSL within 24 hours.": "إذا كان طفل في خطر مباشر، فاتصل بالرقم 999. وأبلِغ بجميع مخاوف حماية الطفل لمسؤول حماية الطفل المعتمد (DSL) لديك خلال 24 ساعة.",
    "QR code linking to the AISA safeguarding training acknowledgment Google Form": "رمز استجابة سريعة يربط بنموذج Google لإقرار تدريب حماية الطفل في AISA",
    "Watch: Safeguarding Briefing": "شاهد: الإحاطة التعريفية بحماية الطفل",
    "Responding: the 5 R's": "التجاوب: خطوات الاستجابة الخمس",
    "Your Team & Counsellors": "فريقك والمرشدون الطلابيون",
    "Complete Your Training": "أكمل تدريبك",
    "Child Safeguarding & Protection — Annual Staff Training": "حماية الطفل ورعايته — التدريب السنوي للموظفين"
};
